name: Ryan Wiesenberg
title: Ryan Wiesenberg - Personal Projects and Blog
tagline: Machine learning, making, game development, and more.
author: Ryan Wiesenberg
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/user_image.jpg

plugins:
  - jekyll-feed
  - jekyll-seo-tag